### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by joshterrill** [MayerDaniel/staticsite#1]
Just wanted to let you know that you have a broken link on this article: https://www.mayer.cool/writings/Process-Injection-101-Hello-World/ pointing here: https://www.mayer.cool/2020/04/20/Process-Injection-102-VirtualProtect/ when it should be pointing here: https://www.mayer.cool/writings/Process-Injection-102-VirtualProtect/

Great articles! :)

**Comment by MayerDaniel** [comment]
https://github.com/MayerDaniel/staticsite/commit/ca49613e485b81cc0d1008dc5f82c5f44632b09b

Fixed, thanks @joshterrill !
